[package]
name = "cpulib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit-vec = "0.6"
primitive-types = "0.12"
byteorder = "1.5"
regex = "1.10"